name: Setup NCNN (macOS)
description: Builds NCNN for macOS
inputs:
  os:
    description: The OS runner name (e.g. macos-15)
    required: true
  ncnn-tag:
    description: The Git tag or commit hash of NCNN to build
    required: true
  vulkan-version:
    description: The version of the Vulkan SDK to use
    required: true

runs:
  using: composite
  steps:
    - name: Define cache key
      id: cache-key
      shell: bash
      run: |
        echo "key=${{ format(
          'setup-ncnn-{0}-{1}-{2}-vulkan-{3}-{4}',
          inputs.os,
          runner.arch,
          inputs.ncnn-tag,
          inputs.vulkan-version,
          hashFiles('.github/cmake-cache/ncnn-base.cmake', '.github/cmake-cache/ncnn-macos.cmake')
        ) }}" >> $GITHUB_OUTPUT

    - name: Restore NCNN
      id: cache-ncnn
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ncnn-dist
        key: ${{ steps.cache-key.outputs.key }}

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@b394a1abed9cb019d8e637eeadac93d73e0853da # v1.5.5
      with:
        vulkan_version: ${{ inputs.vulkan-version }}

    - name: Install dependencies
      shell: bash
      run: brew install libomp

    - name: Checkout ncnn
      if: steps.cache-ncnn.outputs.cache-hit != 'true'
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        repository: Tencent/ncnn
        ref: ${{ inputs.ncnn-tag }}
        path: ncnn
        submodules: recursive

    - name: Configure NCNN
      if: steps.cache-ncnn.outputs.cache-hit != 'true'
      shell: bash
      run: cmake -S ncnn -B build_ncnn -G Ninja
        -C "$GITHUB_WORKSPACE/.github/cmake-cache/ncnn-base.cmake"
        -C "$GITHUB_WORKSPACE/.github/cmake-cache/ncnn-macos.cmake"
        -D Vulkan_LIBRARY="$VULKAN_SDK/lib/libvulkan.dylib"
        -D OpenMP_ROOT="$(brew --prefix libomp)"

    - name: Build NCNN
      if: steps.cache-ncnn.outputs.cache-hit != 'true'
      shell: bash
      run: cmake --build build_ncnn

    - name: Install NCNN
      if: steps.cache-ncnn.outputs.cache-hit != 'true'
      shell: bash
      run: cmake --install build_ncnn --prefix ncnn-dist

    - name: Save NCNN
      if: steps.cache-ncnn.outputs.cache-hit != 'true'
      uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ncnn-dist
        key: ${{ steps.cache-key.outputs.key }}

    - name: Configure NCNN Path
      shell: bash
      run: |
        ncnnRoot=$(realpath ncnn-dist)
        echo "CMAKE_PREFIX_PATH=$ncnnRoot${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}" >> $GITHUB_ENV

        brew_prefix=$(brew --prefix libomp)
        echo "OpenMP_ROOT=$brew_prefix" >> $GITHUB_ENV
        echo "SKBUILD_CMAKE_DEFINE=OpenMP_ROOT=$brew_prefix" >> $GITHUB_ENV

    - name: Upload NCNN
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: ${{ steps.cache-key.outputs.key }}
        path: ncnn-dist
        retention-days: 1
