name: Update Changelog

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  pull-requests: write

jobs:
  update:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true

      - name: Update Changelog and Generate Markdown
        env:
          GH_TOKEN: ${{ github.token }}
        run: uv run --script scripts/generate_changelog.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-update changelog"
          title: "Auto-update changelog"
          body: "This is an automated PR to update the CHANGELOG.md and changelog.json files."
          branch: "update-changelog"
          delete-branch: true
          add-paths: |
            CHANGELOG.md
            changelog.json
